name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        id: run_tests
        run: |
          python -m unittest test_app.py 2>&1 | tee test_results.log
        continue-on-error: true

      - name: Report Test Results
        if: always()
        run: |
          if cat test_results.log | grep -q "OK"; then
            echo "::notice title=Tests Passed!::✅ כל הבדיקות עברו בהצלחה! העבודה שלך מושלמת.🎉"
            exit 0
          else
            echo "::error title=Tests Failed::❌ הבדיקות נכשלו. אנא בדוק את קובץ ה-`test_results.log` לפרטים נוספים."
            cat test_results.log
            exit 1
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-todo:latest
